name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-state
  cancel-in-progress: false

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -lock=false